-- Structural fixture only. No production records or credentials.
create schema private; create schema auth; create schema extensions; create schema vault;
create role anon; create role authenticated; create role service_role;
create function auth.uid() returns uuid language sql as $$
  select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql as $$
  select coalesce(nullif(current_setting('request.jwt.claim.role',true),''),nullif(current_setting('role',true),'none')) $$;
create function public.is_approved_admin() returns boolean language sql as $$
  select coalesce(current_setting('test.admin',true),'false')='true' $$;
create function extensions.pgp_sym_decrypt(bytea,text) returns text language sql as $$ select 'TEST_ONLY'::text $$;
create function extensions.digest(text,text) returns bytea language sql as $$ select decode(md5($1),'hex') $$;
create table vault.decrypted_secrets(name text, decrypted_secret text);
insert into vault.decrypted_secrets values('gate_api_credentials_key','TEST_ONLY');

create table public.copy_system_control (
  "singleton" boolean default true not null,
  "execution_enabled" boolean default false not null,
  "emergency_halted" boolean default true not null,
  "halt_reason" text default 'TRADING_WORKER_NOT_CONFIGURED'::text not null,
  "updated_by" uuid,
  "updated_at" timestamp with time zone default now() not null,
  "max_order_slippage_ratio" numeric default 0.005 not null,
  "broker_channel_id" text default 'maetajak'::text not null,
  constraint "copy_system_control_broker_channel_id_check" CHECK ((broker_channel_id ~ '^[a-z0-9]{1,19}$'::text)),
  constraint "copy_system_control_max_order_slippage_ratio_check" CHECK (((max_order_slippage_ratio >= 0.0001) AND (max_order_slippage_ratio <= 0.03))),
  constraint "copy_system_control_pkey" PRIMARY KEY (singleton),
  constraint "copy_system_control_singleton_check" CHECK (singleton)
);

create table private.trading_accounts (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid,
  "credential_user_id" uuid,
  "account_role" text not null,
  "settle" text default 'usdt'::text not null,
  "status" text default 'DISABLED'::text not null,
  "is_primary" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "trading_accounts_account_role_check" CHECK ((account_role = ANY (ARRAY['MASTER'::text, 'MEMBER'::text]))),
  constraint "trading_accounts_credential_user_id_account_role_settle_key" UNIQUE (credential_user_id, account_role, settle),
  constraint "trading_accounts_pkey" PRIMARY KEY (id),
  constraint "trading_accounts_status_check" CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'DISABLED'::text, 'ERROR'::text, 'HALTED'::text]))),
  constraint "trading_accounts_user_id_account_role_settle_key" UNIQUE (user_id, account_role, settle)
);

create table private.copy_account_snapshots (
  "id" bigint generated by default as identity not null,
  "trading_account_id" uuid not null,
  "total_equity" numeric not null,
  "available_equity" numeric not null,
  "unrealised_pnl" numeric,
  "observed_at" timestamp with time zone not null,
  "source_hash" text not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "copy_account_snapshots_available_equity_check" CHECK ((available_equity >= (0)::numeric)),
  constraint "copy_account_snapshots_pkey" PRIMARY KEY (id),
  constraint "copy_account_snapshots_total_equity_check" CHECK ((total_equity >= (0)::numeric)),
  constraint "copy_account_snapshots_trading_account_id_observed_at_sourc_key" UNIQUE (trading_account_id, observed_at, source_hash)
);

create table private.copy_cycles (
  "id" uuid default gen_random_uuid() not null,
  "master_account_id" uuid not null,
  "master_snapshot_id" bigint,
  "status" text default 'PLANNED'::text not null,
  "source_version" text not null,
  "started_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "error_code" text,
  "created_at" timestamp with time zone default now() not null,
  constraint "copy_cycles_master_account_id_source_version_key" UNIQUE (master_account_id, source_version),
  constraint "copy_cycles_pkey" PRIMARY KEY (id),
  constraint "copy_cycles_status_check" CHECK ((status = ANY (ARRAY['PLANNED'::text, 'RECONCILING'::text, 'COMPLETED'::text, 'PARTIAL'::text, 'ERROR'::text, 'HALTED'::text])))
);

create table public.copy_position_states (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "trading_account_id" uuid not null,
  "contract" text not null,
  "state" text default 'PAUSED'::text not null,
  "target_size" numeric default 0 not null,
  "actual_size" numeric default 0 not null,
  "delta_size" numeric default 0 not null,
  "previous_actual_size" numeric,
  "unexplained_delta" numeric default 0 not null,
  "copy_ratio" numeric not null,
  "max_position_ratio" numeric not null,
  "drift_tolerance_size" numeric default 1 not null,
  "manual_override_confirmed_at" timestamp with time zone,
  "pause_reason" text,
  "last_cycle_id" uuid,
  "last_observed_at" timestamp with time zone,
  "updated_at" timestamp with time zone default now() not null,
  "position_side" text default 'LONG'::text not null,
  "target_leverage" numeric,
  "margin_mode" text,
  "position_mode" text,
  constraint "copy_position_states_account_contract_side_key" UNIQUE (trading_account_id, contract, position_side),
  constraint "copy_position_states_drift_tolerance_size_check" CHECK ((drift_tolerance_size >= (0)::numeric)),
  constraint "copy_position_states_pkey" PRIMARY KEY (id),
  constraint "copy_position_states_position_side_check" CHECK ((position_side = ANY (ARRAY['LONG'::text, 'SHORT'::text]))),
  constraint "copy_position_states_state_check" CHECK ((state = ANY (ARRAY['SYNCED'::text, 'DRIFT'::text, 'MANUAL_OVERRIDE'::text, 'PAUSED'::text, 'REDUCE_ONLY'::text, 'ERROR'::text, 'HALTED'::text])))
);

create table public.copy_events (
  "id" bigint generated by default as identity not null,
  "user_id" uuid,
  "contract" text,
  "event_type" text not null,
  "severity" text default 'INFO'::text not null,
  "cycle_id" uuid,
  "safe_payload" jsonb default '{}'::jsonb not null,
  "occurred_at" timestamp with time zone default now() not null,
  "position_side" text,
  constraint "copy_events_event_type_check" CHECK ((event_type = ANY (ARRAY['MASTER_POSITION_CHANGED'::text, 'TARGET_POSITION_CALCULATED'::text, 'DELTA_ORDER_PLANNED'::text, 'ORDER_SUBMITTED'::text, 'ORDER_FILLED'::text, 'ORDER_UNKNOWN'::text, 'POSITION_SYNCED'::text, 'MANUAL_OVERRIDE_DETECTED'::text, 'SYMBOL_PAUSED'::text, 'RISK_REDUCE_ONLY'::text, 'MEMBER_HALTED'::text, 'SYSTEM_HALTED'::text, 'ERROR'::text]))),
  constraint "copy_events_pkey" PRIMARY KEY (id),
  constraint "copy_events_position_side_check" CHECK (((position_side IS NULL) OR (position_side = ANY (ARRAY['LONG'::text, 'SHORT'::text])))),
  constraint "copy_events_severity_check" CHECK ((severity = ANY (ARRAY['INFO'::text, 'WARNING'::text, 'CRITICAL'::text])))
);

create table private.copy_order_intents (
  "id" uuid default gen_random_uuid() not null,
  "cycle_id" uuid not null,
  "user_id" uuid not null,
  "trading_account_id" uuid not null,
  "contract" text not null,
  "target_size" numeric not null,
  "actual_size_at_plan" numeric not null,
  "delta_size" numeric not null,
  "reduce_only" boolean default false not null,
  "idempotency_key" text not null,
  "gate_order_text" text not null,
  "status" text default 'PLANNED'::text not null,
  "gate_order_id" text,
  "filled_size" numeric default 0 not null,
  "average_fill_price" numeric,
  "submit_attempts" integer default 0 not null,
  "next_attempt_at" timestamp with time zone default now() not null,
  "last_error_code" text,
  "created_at" timestamp with time zone default now() not null,
  "submitted_at" timestamp with time zone,
  "resolved_at" timestamp with time zone,
  "updated_at" timestamp with time zone default now() not null,
  "position_side" text default 'LONG'::text not null,
  "target_leverage" numeric,
  "margin_mode" text,
  "position_mode" text,
  "pid" text,
  constraint "copy_order_intents_cycle_account_contract_side_key" UNIQUE (cycle_id, trading_account_id, contract, position_side),
  constraint "copy_order_intents_delta_size_check" CHECK ((delta_size <> (0)::numeric)),
  constraint "copy_order_intents_gate_order_text_key" UNIQUE (gate_order_text),
  constraint "copy_order_intents_idempotency_key_key" UNIQUE (idempotency_key),
  constraint "copy_order_intents_pkey" PRIMARY KEY (id),
  constraint "copy_order_intents_position_side_check" CHECK ((position_side = ANY (ARRAY['LONG'::text, 'SHORT'::text]))),
  constraint "copy_order_intents_status_check" CHECK ((status = ANY (ARRAY['PLANNED'::text, 'QUEUED'::text, 'SUBMITTING'::text, 'ACKNOWLEDGED'::text, 'PARTIALLY_FILLED'::text, 'FILLED'::text, 'CANCELLED'::text, 'REJECTED'::text, 'UNKNOWN'::text])))
);

create table private.copy_order_attempts (
  "id" bigint generated by default as identity not null,
  "intent_id" uuid not null,
  "attempt_number" integer not null,
  "request_fingerprint" text not null,
  "http_status" integer,
  "gate_label" text,
  "result_status" text not null,
  "safe_response" jsonb default '{}'::jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "copy_order_attempts_intent_id_attempt_number_key" UNIQUE (intent_id, attempt_number),
  constraint "copy_order_attempts_pkey" PRIMARY KEY (id),
  constraint "copy_order_attempts_result_status_check" CHECK ((result_status = ANY (ARRAY['ACKNOWLEDGED'::text, 'REJECTED'::text, 'TIMEOUT'::text, 'NETWORK_ERROR'::text, 'UNKNOWN'::text])))
);

create table private.copy_reconciliation_jobs (
  "id" bigint generated by default as identity not null,
  "intent_id" uuid not null,
  "attempts" integer default 0 not null,
  "run_after" timestamp with time zone default now() not null,
  "claimed_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "copy_reconciliation_jobs_intent_id_key" UNIQUE (intent_id),
  constraint "copy_reconciliation_jobs_pkey" PRIMARY KEY (id)
);

create table private.member_copy_onboarding_baselines (
  "trading_account_id" uuid not null,
  "positions" jsonb default '[]'::jsonb not null,
  "initialized_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "member_positions" jsonb default '[]'::jsonb not null,
  constraint "member_copy_onboarding_baselines_member_positions_array" CHECK ((jsonb_typeof(member_positions) = 'array'::text)),
  constraint "member_copy_onboarding_baselines_pkey" PRIMARY KEY (trading_account_id),
  constraint "member_copy_onboarding_baselines_positions_check" CHECK ((jsonb_typeof(positions) = 'array'::text))
);

create table private.copy_current_accounts (
  "trading_account_id" uuid not null,
  "user_id" uuid,
  "account_role" text not null,
  "total_equity" numeric not null,
  "available_equity" numeric not null,
  "unrealised_pnl" numeric,
  "equity_day" date not null,
  "day_start_equity" numeric not null,
  "peak_equity" numeric not null,
  "source_hash" text not null,
  "copy_cycle_id" uuid,
  "observed_at" timestamp with time zone not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "copy_current_accounts_account_role_check" CHECK ((account_role = ANY (ARRAY['MASTER'::text, 'MEMBER'::text]))),
  constraint "copy_current_accounts_available_equity_check" CHECK ((available_equity >= (0)::numeric)),
  constraint "copy_current_accounts_day_start_equity_check" CHECK ((day_start_equity >= (0)::numeric)),
  constraint "copy_current_accounts_peak_equity_check" CHECK ((peak_equity >= (0)::numeric)),
  constraint "copy_current_accounts_pkey" PRIMARY KEY (trading_account_id),
  constraint "copy_current_accounts_total_equity_check" CHECK ((total_equity >= (0)::numeric))
);

create table private.copy_position_snapshots (
  "id" bigint generated by default as identity not null,
  "account_snapshot_id" bigint not null,
  "trading_account_id" uuid not null,
  "contract" text not null,
  "size" numeric not null,
  "mark_price" numeric not null,
  "entry_price" numeric,
  "leverage" numeric,
  "quanto_multiplier" numeric not null,
  "observed_at" timestamp with time zone not null,
  "created_at" timestamp with time zone default now() not null,
  "position_side" text default 'LONG'::text not null,
  constraint "copy_position_snapshots_account_contract_side_key" UNIQUE (account_snapshot_id, contract, position_side),
  constraint "copy_position_snapshots_mark_price_check" CHECK ((mark_price > (0)::numeric)),
  constraint "copy_position_snapshots_pkey" PRIMARY KEY (id),
  constraint "copy_position_snapshots_quanto_multiplier_check" CHECK ((quanto_multiplier > (0)::numeric))
);

create table public.profiles (
  "id" uuid not null,
  "email" text not null,
  "full_name" text default ''::text not null,
  "phone" text default ''::text not null,
  "role" text default 'MEMBER'::text not null,
  "approval_status" text default 'PENDING'::text not null,
  "terms_accepted_at" timestamp with time zone,
  "approved_at" timestamp with time zone,
  "approved_by" uuid,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "copy_ratio" numeric default 100 not null,
  "max_position_ratio" numeric default 30 not null,
  "terms_version" text,
  "privacy_version" text,
  "copy_started_at" timestamp with time zone,
  "copy_paused" boolean default false not null,
  "member_halted" boolean default false not null,
  "reduce_only" boolean default false not null,
  "daily_loss_limit_pct" numeric default 5 not null,
  "max_drawdown_pct" numeric default 15 not null,
  "max_leverage" numeric default 10 not null,
  "close_positions_requested" boolean default false not null,
  "nickname" text,
  constraint "profiles_approval_status_check" CHECK ((approval_status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'SUSPENDED'::text]))),
  constraint "profiles_copy_ratio_check" CHECK ((((copy_ratio >= (50)::numeric) AND (copy_ratio <= (200)::numeric)) AND (mod(copy_ratio, (10)::numeric) = (0)::numeric))),
  constraint "profiles_daily_loss_limit_pct_check" CHECK (((daily_loss_limit_pct >= 0.1) AND (daily_loss_limit_pct <= (100)::numeric))),
  constraint "profiles_max_drawdown_pct_check" CHECK (((max_drawdown_pct >= 0.1) AND (max_drawdown_pct <= (100)::numeric))),
  constraint "profiles_max_leverage_check" CHECK (((max_leverage >= (1)::numeric) AND (max_leverage <= (100)::numeric))),
  constraint "profiles_max_position_ratio_check" CHECK ((((max_position_ratio >= (20)::numeric) AND (max_position_ratio <= (50)::numeric)) AND (mod(max_position_ratio, (10)::numeric) = (0)::numeric))),
  constraint "profiles_nickname_length_check" CHECK (((nickname IS NULL) OR ((char_length(TRIM(BOTH FROM nickname)) >= 2) AND (char_length(TRIM(BOTH FROM nickname)) <= 20)))),
  constraint "profiles_pkey" PRIMARY KEY (id),
  constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['MEMBER'::text, 'ADMIN'::text])))
);

create table public.admin_audit_logs (
  "id" bigint generated by default as identity not null,
  "actor_id" uuid,
  "action" text not null,
  "target_user_id" uuid,
  "previous_value" jsonb,
  "next_value" jsonb,
  "created_at" timestamp with time zone default now() not null,
  constraint "admin_audit_logs_pkey" PRIMARY KEY (id)
);

create table private.gate_api_credentials (
  "user_id" uuid not null,
  "gate_uid" text not null,
  "api_key_ciphertext" bytea not null,
  "secret_key_ciphertext" bytea not null,
  "api_key_last4" text not null,
  "status" text default 'PENDING_VERIFICATION'::text not null,
  "futures_read" boolean default false not null,
  "futures_trade" boolean default false not null,
  "ip_whitelisted" boolean default false not null,
  "withdrawal_disabled" boolean default true not null,
  "last_error" text,
  "verified_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "connection_role" text default 'MEMBER'::text not null,
  "permissions_confirmed" boolean default false not null,
  "gate_user_id" text,
  "last_checked_at" timestamp with time zone,
  "last_error_code" text,
  "verification_version" integer default 1 not null,
  "verified_worker_ip" inet,
  constraint "gate_api_credentials_connection_role_check" CHECK ((connection_role = ANY (ARRAY['MEMBER'::text, 'MASTER'::text]))),
  constraint "gate_api_credentials_pkey" PRIMARY KEY (user_id),
  constraint "gate_api_credentials_status_check" CHECK ((status = ANY (ARRAY['PENDING_VERIFICATION'::text, 'VERIFYING'::text, 'VERIFIED'::text, 'ERROR'::text, 'DISABLED'::text])))
);

create table private.copy_snapshot_checkpoints (
  "trading_account_id" uuid not null,
  "account_snapshot_at" timestamp with time zone,
  "position_snapshot_at" timestamp with time zone,
  "position_structure_hash" text not null,
  "updated_at" timestamp with time zone default now() not null,
  constraint "copy_snapshot_checkpoints_pkey" PRIMARY KEY (trading_account_id)
);

create table private.copy_worker_runtime (
  "singleton" boolean default true not null,
  "worker_id" text,
  "worker_version" text,
  "gate_base_url" text,
  "public_ip" inet,
  "mode" text default 'OBSERVE'::text not null,
  "heartbeat_at" timestamp with time zone,
  "last_test_passed_at" timestamp with time zone,
  "started_at" timestamp with time zone,
  "updated_at" timestamp with time zone default now() not null,
  "consecutive_failures" integer default 0 not null,
  "last_success_at" timestamp with time zone,
  "last_error_code" text,
  "broker_channel_id" text,
  constraint "copy_worker_runtime_broker_channel_id_check" CHECK (((broker_channel_id IS NULL) OR (broker_channel_id ~ '^[a-z0-9]{1,19}$'::text))),
  constraint "copy_worker_runtime_mode_check" CHECK ((mode = ANY (ARRAY['OBSERVE'::text, 'DRY_RUN'::text, 'LIVE'::text]))),
  constraint "copy_worker_runtime_pkey" PRIMARY KEY (singleton),
  constraint "copy_worker_runtime_singleton_check" CHECK (singleton)
);
