-- Position-entry notifications are durable and never enable copy execution.
do $$ begin
  if not exists(select 1 from public.copy_system_control where singleton and not execution_enabled and emergency_halted) then
    raise exception 'HALTED_DEPLOYMENT_REQUIRED';
  end if;
end $$;

create table private.copy_entry_alert_outbox (
  id bigint generated by default as identity primary key,
  intent_id uuid not null unique references private.copy_order_intents(id) on delete cascade,
  event_type text not null default 'COPY_POSITION_ENTRY_FILLED',
  safe_payload jsonb not null,
  attempts integer not null default 0,
  claimed_at timestamptz,
  next_attempt_at timestamptz not null default now(),
  delivered_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint copy_entry_alert_payload_object check(jsonb_typeof(safe_payload)='object'),
  constraint copy_entry_alert_attempts_nonnegative check(attempts>=0)
);
alter table private.copy_entry_alert_outbox enable row level security;
revoke all on private.copy_entry_alert_outbox from public,anon,authenticated;
create index copy_entry_alert_delivery_idx on private.copy_entry_alert_outbox(next_attempt_at,id)
  where delivered_at is null;

create function private.queue_copy_entry_alert()
returns trigger language plpgsql security definer set search_path=pg_catalog
as $$
declare member_label text;
begin
  if new.reduce_only or new.filled_size=0
    or (new.status<>'FILLED' and not new.exchange_terminal)
    or (old.filled_size<>0 and (old.status='FILLED' or old.exchange_terminal)) then
    return new;
  end if;
  select coalesce(nullif(p.nickname,''),nullif(p.full_name,''),'회원 계정') into member_label
  from public.profiles p where p.id=new.user_id;
  insert into private.copy_entry_alert_outbox(intent_id,safe_payload)
  values(new.id,jsonb_build_object(
    'member',coalesce(member_label,'회원 계정'),
    'contract',new.contract,
    'position_side',new.position_side,
    'filled_size',abs(new.filled_size),
    'average_fill_price',new.average_fill_price,
    'target_leverage',new.target_leverage,
    'margin_mode',new.margin_mode,
    'result_status',new.status
  )) on conflict(intent_id) do nothing;
  return new;
end;
$$;
revoke all on function private.queue_copy_entry_alert() from public,anon,authenticated;
create trigger queue_copy_entry_alert after update of filled_size,status,exchange_terminal
on private.copy_order_intents for each row execute function private.queue_copy_entry_alert();

create function public.claim_copy_entry_alerts(p_limit integer default 10)
returns table(alert_id bigint,event_type text,details jsonb)
language plpgsql security definer set search_path=pg_catalog
as $$
begin
  perform private.require_copy_worker_role();
  return query with candidates as (
    select o.id from private.copy_entry_alert_outbox o
    where o.delivered_at is null and o.next_attempt_at<=clock_timestamp()
      and (o.claimed_at is null or o.claimed_at<clock_timestamp()-interval '2 minutes')
    order by o.next_attempt_at,o.id for update skip locked
    limit greatest(1,least(coalesce(p_limit,10),50))
  ), claimed as (
    update private.copy_entry_alert_outbox o set claimed_at=clock_timestamp(),attempts=o.attempts+1,updated_at=now()
    from candidates c where o.id=c.id returning o.id,o.event_type,o.safe_payload
  ) select c.id,c.event_type,c.safe_payload from claimed c;
end;
$$;
revoke all on function public.claim_copy_entry_alerts(integer) from public,anon,authenticated;
grant execute on function public.claim_copy_entry_alerts(integer) to service_role;

create function public.complete_copy_entry_alert(p_alert_id bigint,p_sent boolean,p_error_code text default null)
returns void language plpgsql security definer set search_path=pg_catalog
as $$
begin
  perform private.require_copy_worker_role();
  update private.copy_entry_alert_outbox o set
    delivered_at=case when p_sent then clock_timestamp() else o.delivered_at end,
    claimed_at=null,
    next_attempt_at=case when p_sent then o.next_attempt_at else clock_timestamp()+make_interval(secs=>least(300,30*(2^least(o.attempts,4))::integer)) end,
    last_error_code=case when p_sent then null else left(coalesce(p_error_code,'ALERT_DELIVERY_FAILED'),80) end,
    updated_at=now()
  where o.id=p_alert_id and o.delivered_at is null;
end;
$$;
revoke all on function public.complete_copy_entry_alert(bigint,boolean,text) from public,anon,authenticated;
grant execute on function public.complete_copy_entry_alert(bigint,boolean,text) to service_role;

notify pgrst,'reload schema';
